#!/bin/bash
#
# Copyright © 2026 Mnèmê (u5=001777236237.945e_43.30_005.38) <mneme@foopgp.org>
#
# SPDX-License-Identifier: LGPL-3.0-only
#
# Regenerate share/bash-libs/svg/card.svg from:
#   foopgp-hugowebsite/resources/svg/foopgp_card_fr.svg  (top zone, 30mm — uniform scale)
#   bin/bl-pgpid's inline BL_PGPID_STICKER_TEMPLATE      (bottom zone, 25mm verbatim)
# Run after editing either source.
set -e

REPO=/home/u5001777236237.945e_43.30_005.38/git/foopgp/bash-libs
FOOPGP_CARD=/home/u5001777236237.945e_43.30_005.38/git/foopgp/foopgp-hugowebsite/resources/svg/foopgp_card_fr.svg

foopgp_body=$(FOOPGP_CARD="$FOOPGP_CARD" python3 - <<'PY'
import os, re, sys
src = open(os.environ["FOOPGP_CARD"]).read()
body = re.sub(r'^.*?<svg[^>]*>', '', src, count=1, flags=re.S)
body = re.sub(r'</svg>\s*$', '', body, count=1, flags=re.S)
body = re.sub(r'<script[^>]*>.*?</script>', '', body, count=1, flags=re.S)
body = re.sub(r'<metadata[^>]*>.*?</metadata>', '', body, count=1, flags=re.S)
body = re.sub(r'<defs[^/]*/>', '', body, count=1, flags=re.S)
# drop the subtitle <path id="text3766" .../>
body = re.sub(r'<path[^>]*id="text3766"[^/]*/>', '', body, count=1, flags=re.S)
# drop the lower cream <rect id="rect366" .../> — we put the sticker there instead
body = re.sub(r'<rect[^>]*id="rect366"[^/]*/>', '', body, count=1, flags=re.S)
# drop the outer dark <rect id="rect366-3" .../> — card.svg provides its own dark backdrop sized to the top zone
body = re.sub(r'<rect[^>]*id="rect366-3"[^/]*/>', '', body, count=1, flags=re.S)
sys.stdout.write(body)
PY
)

sticker_body=$(REPO="$REPO" python3 - <<'PY'
import os, re, sys
src = open(os.path.join(os.environ["REPO"], "bin/bl-pgpid")).read()
# Extract the inline sticker template — single-quoted bash here, with '\'' escapes around CSS font names.
m = re.search(r"declare -r BL_PGPID_STICKER_TEMPLATE='(.*?)'\n", src, flags=re.S)
if not m:
    sys.exit("BL_PGPID_STICKER_TEMPLATE not found in bin/bl-pgpid")
sticker = m.group(1).replace("'\\''", "'")
# Strip the XML prolog and the outer <svg ...> wrapper — we re-wrap as a nested <svg>.
sticker = re.sub(r'^.*?<svg[^>]*>', '', sticker, count=1, flags=re.S)
sticker = re.sub(r'</svg>\s*$', '', sticker, count=1, flags=re.S)
sys.stdout.write(sticker)
PY
)

OUT="$REPO/share/bash-libs/svg/card.svg"
cat > "$OUT" <<EOF
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--
  Business card template — 85mm × 55mm (European business-card standard).
  Generated by tools/build_card.sh from:
    foopgp-hugowebsite/resources/svg/foopgp_card_fr.svg  (top zone, 30mm — uniform scale)
    bin/bl-pgpid's BL_PGPID_STICKER_TEMPLATE             (bottom zone, 25mm verbatim)
  Pug aspect ratio preserved via preserveAspectRatio="xMidYMid meet".
  Stripped from foopgp_card_fr.svg: outer dark rect (we draw our own backdrop)
  and the handwriting cream rect (replaced by the sticker).
  Placeholders (envsubst):
      \${SUBTITLE}                    (i18n, see bl-pgpid)
      \${NAME} \${U4} \${FPR_LINE1} \${FPR_LINE2} \${EMAIL} \${QR_HREF}
-->
<svg xmlns="http://www.w3.org/2000/svg"
     xmlns:xlink="http://www.w3.org/1999/xlink"
     version="1.1"
     width="85mm" height="55mm"
     viewBox="0 0 85 55">

  <!-- Top zone backdrop — dark band sized 30mm so the pug's "meet" padding still reads dark -->
  <rect x="0" y="0" width="85" height="30" fill="#1a1a37"/>

  <!-- Top zone — foopgp_card_fr.svg's dark band (viewBox cropped to y=0..105),
       scaled uniformly so the pug keeps its aspect ratio. -->
  <svg x="0" y="0" width="85" height="30"
       viewBox="0 0 336.37794 105"
       preserveAspectRatio="xMidYMid meet">${foopgp_body}
    <text x="168.19" y="95"
          font-family="DejaVu Sans, sans-serif" font-style="italic"
          font-size="16" fill="#ffffff" text-anchor="middle">\${SUBTITLE}</text>
  </svg>

  <!-- Bottom zone (25mm) — sticker block from bl-pgpid's BL_PGPID_STICKER_TEMPLATE -->
  <svg x="0" y="30" width="85" height="25" viewBox="0 0 85 25">${sticker_body}</svg>
</svg>
EOF
xmllint --noout "$OUT" && echo "card.svg: valid XML"
wc -l "$OUT"
