#!/bin/bash
set -e
foopgp_body=$(python3 - <<'PY'
import re, sys
src = open("/home/u5001777236237.945e_43.30_005.38/git/foopgp/foopgp-hugowebsite/resources/svg/foopgp_card_fr.svg").read()
body = re.sub(r'^.*?<svg[^>]*>', '', src, count=1, flags=re.S)
body = re.sub(r'</svg>\s*$', '', body, count=1, flags=re.S)
body = re.sub(r'<script[^>]*>.*?</script>', '', body, count=1, flags=re.S)
body = re.sub(r'<metadata[^>]*>.*?</metadata>', '', body, count=1, flags=re.S)
body = re.sub(r'<defs[^/]*/>', '', body, count=1, flags=re.S)
# drop the subtitle <path id="text3766" .../>
body = re.sub(r'<path[^>]*id="text3766"[^/]*/>', '', body, count=1, flags=re.S)
# drop the lower cream <rect id="rect366" .../> — it was the original handwriting zone; we put the sticker there instead
body = re.sub(r'<rect[^>]*id="rect366"[^/]*/>', '', body, count=1, flags=re.S)
sys.stdout.write(body)
PY
)

sticker_body=$(python3 - <<'PY'
import re, sys
src = open("/home/u5001777236237.945e_43.30_005.38/git/foopgp/bash-libs/share/bash-libs/svg/sticker.svg").read()
body = re.sub(r'^.*?<svg[^>]*>', '', src, count=1, flags=re.S)
body = re.sub(r'</svg>\s*$', '', body, count=1, flags=re.S)
sys.stdout.write(body)
PY
)

OUT=/home/u5001777236237.945e_43.30_005.38/git/foopgp/bash-libs/share/bash-libs/svg/card.svg
cat > "$OUT" <<EOF
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--
  Business card template — 89mm × 59mm.
  Generated by tools/build_card.sh from:
    foopgp-hugowebsite/resources/svg/foopgp_card_fr.svg  (top zone, vertically compressed to 34mm)
    bash-libs/share/bash-libs/svg/sticker.svg            (bottom zone, verbatim 25mm)
  The original handwriting-zone <rect id="rect366"/> from foopgp_card_fr.svg
  is stripped, since the sticker replaces it.
  Placeholders (envsubst):
      \${SUBTITLE}                    (i18n, see bl-pgpid)
      \${NAME} \${U4} \${FPR_LINE1} \${FPR_LINE2} \${EMAIL} \${QR_HREF}
-->
<svg xmlns="http://www.w3.org/2000/svg"
     xmlns:xlink="http://www.w3.org/1999/xlink"
     version="1.1"
     width="89mm" height="59mm"
     viewBox="0 0 89 59">

  <!-- Top zone (34mm) — foopgp_card_fr.svg's dark band only.  We crop the nested
       viewBox to the dark zone (y=0..105) so the pug + foopgp.org wordmark + subtitle
       are sized to the actual band, rather than landing in a tiny strip at the top
       with empty dark filling the rest. preserveAspectRatio="none" stretches to fill. -->
  <svg x="0" y="0" width="89" height="34"
       viewBox="0 0 336.37794 105"
       preserveAspectRatio="none">${foopgp_body}
    <text x="168.19" y="95"
          font-family="DejaVu Sans, sans-serif" font-style="italic"
          font-size="16" fill="#ffffff" text-anchor="middle">\${SUBTITLE}</text>
  </svg>

  <!-- Bottom zone (25mm) — sticker.svg verbatim -->
  <svg x="0" y="34" width="89" height="25" viewBox="0 0 89 25">${sticker_body}</svg>
</svg>
EOF
xmllint --noout "$OUT" && echo "card.svg: valid XML"
wc -l "$OUT"
